
# Site
title:              FillixForFun
bio:                "Live Long and Prosper."
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'

# Jekyll
markdown:           kramdown
sass:
  sass_dir:         _sass
  style:            compressed
